apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: torsim-proxy
  name: torsim-proxy
spec:
  replicas: 1
  selector:
    app: torsim-proxy
  template:
    metadata:
      labels:
        app: torsim-proxy
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "80"
        - name: SERVER_USE_FORWARD_HEADERS
          value: "true"
        - name: ZUUL_ROUTES_DATABASE_API_URL
          value: http://torsim-database
        - name: ZUUL_ROUTES_ADB_API_URL
          value: http://torsim-adb
        - name: ZUUL_ROUTES_LOG_API_URL
          value: http://torsim-message-processor
        - name: SERVER_PORT
          value: "80"
        - name: SERVER_PORT
          value: "80"
        image: dr.safetech:54432/torsim-proxy:10
        name: torsim-proxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: torsim-proxy
  name: torsim-proxy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http
  selector:
    app: torsim-proxy
  type: NodePort
