server:
  use-forward-headers: true
  port: 8081

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 200
    max-per-route-connections: 20
    time-unit: MILLISECONDS
    time-to-live: 10000
  routes:
    database-api:
      url: "http://localhost:8082"

ribbon:
  eureka:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  security:
    enabled: false

info:
  app:
    name: UI
    description: Main UI and Gateway application
    version: 1.0.0-DEMO

spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  servlet:
    multipart: 
      max-file-size: 100MB
      max-request-size: 100MB
